POST  https://api.hbdm.pro/api/v1/contract_account_info?AccessKeyId=yh4fhmvs5k-03fc159f-08144b93-a9694&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2019-12-02T01:37:37&symbol=BTC&Signature=LFxKK9slYqZBJoJgeGLI39XKaMx94MgcDvR1pKEQh4A=%27
###

GET https://api.huzhihui.org.cn/doc HTTP/1.1